#!/bin/bash

echo "🔄 Updating project status from PLANNING to RECRUITING..."
echo ""
echo "Please run this SQL command in your database:"
echo ""
echo "Option 1: Using Docker container"
echo "--------------------------------"
echo "docker exec -i \$(docker ps --filter 'ancestor=postgres' -q | head -1) psql -U username -d kolabit << EOF"
echo "UPDATE projects SET status = 'RECRUITING' WHERE status = 'PLANNING';"
echo "SELECT id, title, status FROM projects;"
echo "EOF"
echo ""
echo "Option 2: Direct psql (if database is accessible)"
echo "--------------------------------------------------"
echo "psql -U username -h localhost -d kolabit << EOF"
echo "UPDATE projects SET status = 'RECRUITING' WHERE status = 'PLANNING';"
echo "SELECT id, title, status FROM projects;"
echo "EOF"
echo ""
echo "Option 3: Using Prisma Studio"
echo "------------------------------"
echo "npx prisma studio"
echo "Then manually update status field from PLANNING to RECRUITING"
echo ""
